name: favoritosdoyoutubs
description: Aplicativo flutter desenvolvido como complementação do curso da Udemy &quot;Criação de Apps Android e iOS com Flutter - Crie 16 Apps&quot;, de Daniel Ciolfi.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_youtube: ^2.0.0
  http: ^0.12.1
  shared_preferences: ^0.5.7
  rxdart: ^0.24.0
  bloc_pattern: ^1.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/youtube_logo.png
  #  - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic